baseURL = "https://lokal.ninja/hamburg"
languageCode = "de-DE"
title = "Lokal Ninja - Hamburg"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Hamburg"
  repo = "hamburg"
