baseURL = "https://de.shoogle.net/hamburg/"
languageCode = "de"
title = "Hamburg"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "hamburg"

[taxonomies]
  shop = "shops"

